look for error exit code

diff --git a/tests/checksums b/tests/checksums
--- a/tests/checksums
+++ b/tests/checksums
@@ -1,4 +1,4 @@
-#!/bin/sh -x
+#!/bin/sh
 
 # Copyright (C) 1994-2016 Lawrence Livermore National Security, LLC.
 # LLNL-CODE-425250.
@@ -158,7 +158,7 @@ fi
 # detect a checksumming error.
 #
 brOut=$($browser --proper-exit-code -q -c -e block2/fl1 multi_ucd3d_corrupt.h5 2>&1)
-if [ $? -ne 0 ] || [ -z "$(echo $brOut | grep 'Checksum failure')" ]; then
+if [ $? -eq 0 ] || [ -z "$(echo $brOut | grep 'Checksum failure')" ]; then
     result=1
 fi
 
