Updates version number to 4.7.1-pre2 Fixes problems with writing edge|face centered data. Adds auto swapping of slash character in the filename portion of mutli-block objects. Adds support for penetrating datasets in HDF5 driver's /.silo dir from within browser. Adds support for labeling variables as 'conserved' quantities. Adds support for labeling variables as 'extensive' quantities. Fixes browser output so that all metadata for an object is output before all problem     sized data for the object. Adds support for HDF5 hard links for friendly names Fixes silock to operate on HDF5-based files. Fixes a coreing bug where db_SplitShapelist() was called on a zonelist read with     a readmask that prevented Zonelist info from being read. Fixes a minor bug in DBCLOSE in fortran wrappers where dbid was not set to -1 Makes all Silo's structs non-anonymous Fixes a problem with silo's magic file where leading '!' in PDB moniker gets     interpreted as 'not equal' operator. Adds a test for silock to catch nans and infs. Documentation update
git-svn-id: file:///usr/gapps/silo/svn/trunk@117 92378438-2262-0410-827d-edb41c1c42c8

diff --git a/tests/testsuite b/tests/testsuite
--- a/tests/testsuite
+++ b/tests/testsuite
@@ -626,7 +626,7 @@ at_times_file=$at_suite_dir/at-times
 # List of the tested programs.
 at_tested=''
 # List of the all the test groups.
-at_groups_all=' banner-1 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 banner-2 38 39 40 banner-3 41 banner-4 42 43 44 45 46 47 48 49 50 51 banner-5 52 53 54 55 56 57 58 banner-6 59 60 61'
+at_groups_all=' banner-1 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 banner-2 38 39 40 banner-3 41 banner-4 42 43 44 45 46 47 48 49 50 51 banner-5 52 53 54 55 56 57 58 banner-6 59 60 61 62'
 # As many question marks as there are digits in the last test group number.
 # Used to normalize the test group numbers so that `ls' lists them in
 # numerical order.
@@ -690,9 +690,10 @@ at_help_all="1;testsuite.at:11;version;;
 56;testsuite.at:235;quadf77;fortran;
 57;testsuite.at:239;testallf77;fortran;
 58;testsuite.at:243;ucdf77;fortran;
-59;testsuite.at:249;multi_file;large;
-60;testsuite.at:253;testall -medium;large;
-61;testsuite.at:257;testall -large;large;
+59;testsuite.at:249;silock;tools;
+60;testsuite.at:253;multi_file;large;
+61;testsuite.at:257;testall -medium;large;
+62;testsuite.at:261;testall -large;large;
 "
 
 at_prev=
@@ -916,7 +917,7 @@ fi
 # List of tests.
 if $at_list_p; then
   cat <<_ATEOF
-silo 4.7.1-pre1 test suite: VALGRIND="$VALGRIND" DB_HDF5="$DB_HDF5" test groups:
+silo 4.7.1-pre2 test suite: VALGRIND="$VALGRIND" DB_HDF5="$DB_HDF5" test groups:
 
  NUM: FILE-NAME:LINE     TEST-GROUP-NAME
       KEYWORDS
@@ -940,7 +941,7 @@ _ATEOF
   exit 0
 fi
 if $at_version_p; then
-  echo "$as_me (silo 4.7.1-pre1)"
+  echo "$as_me (silo 4.7.1-pre2)"
   cat <<\_ACEOF
 
 Copyright (C) 2000, 2001, 2002, 2003, 2004, 2005, 2006 Free Software
@@ -1029,11 +1030,11 @@ exec 5>>"$at_suite_log"
 
 # Banners and logs.
 sed 'h;s/./-/g;s/^.../## /;s/...$/ ##/;p;x;p;x' <<_ASBOX
-## silo 4.7.1-pre1 test suite: VALGRIND="$VALGRIND" DB_HDF5="$DB_HDF5". ##
+## silo 4.7.1-pre2 test suite: VALGRIND="$VALGRIND" DB_HDF5="$DB_HDF5". ##
 _ASBOX
 {
   sed 'h;s/./-/g;s/^.../## /;s/...$/ ##/;p;x;p;x' <<_ASBOX
-## silo 4.7.1-pre1 test suite: VALGRIND="$VALGRIND" DB_HDF5="$DB_HDF5". ##
+## silo 4.7.1-pre2 test suite: VALGRIND="$VALGRIND" DB_HDF5="$DB_HDF5". ##
 _ASBOX
   echo
 
@@ -1292,15 +1293,15 @@ _ATEOF
 cat >expout <<'_ATEOF'
 This version of Silo is greater than or equal to 4.6
 This version of Silo is NOT greater than or equal to 90.5.2
-DBVersion() returns "4.7.1-pre1"
+DBVersion() returns "4.7.1-pre2"
 DBVersionGE(4,6,0) returns 1
 DBVersionGE(90,5,2) returns 0
 On file handle returned from DBCreate...
-    DBFileVersion() returns "4.7.1-pre1"
+    DBFileVersion() returns "4.7.1-pre2"
     DBFileVersionGE(4,6,0) returns 1
     DBFileVersionGE(90,5,2) returns 0
 On file handle returned from DBOpen...
-    DBFileVersion() returns "4.7.1-pre1"
+    DBFileVersion() returns "4.7.1-pre2"
     DBFileVersionGE(4,6,0) returns 1
     DBFileVersionGE(90,5,2) returns 0
 On old silo file handle returned from DBOpen...
@@ -4913,10 +4914,10 @@ Special
 _ATEOF
     ;;
 
-  59 ) # 59. testsuite.at:249: multi_file
+  59 ) # 59. testsuite.at:249: silock
     at_setup_line='testsuite.at:249'
-    at_desc="multi_file"
-    $at_quiet $ECHO_N " 59: multi_file                                     $ECHO_C"
+    at_desc="silock"
+    $at_quiet $ECHO_N " 59: silock                                         $ECHO_C"
     at_xfail=no
     echo "#                             -*- compilation -*-" >> "$at_group_log"
     (
@@ -4925,30 +4926,26 @@ _ATEOF
 
 
 $at_traceoff
-echo "$at_srcdir/testsuite.at:251: \$VALGRIND multi_file \$DB_HDF5"
+echo "$at_srcdir/testsuite.at:251: testsilock \`pwd\` \$DB_HDF5"
 echo testsuite.at:251 >"$at_check_line_file"
 
 at_trace_this=
 if test -n "$at_traceon"; then
-    case "$VALGRIND multi_file $DB_HDF5" in
-        *'
-'*) echo 'Not enabling shell tracing (command contains an embedded newline)' ;;
- *) at_trace_this=yes ;;
-    esac
+    echo 'Not enabling shell tracing (command contains a `...` command substitution)'
 fi
 
 if test -n "$at_trace_this"; then
-    ( $at_traceon; $VALGRIND multi_file $DB_HDF5 ) >"$at_stdout" 2>"$at_stder1"
+    ( $at_traceon; testsilock `pwd` $DB_HDF5 ) >"$at_stdout" 2>"$at_stder1"
     at_status=$?
     grep '^ *+' "$at_stder1" >&2
     grep -v '^ *+' "$at_stder1" >"$at_stderr"
 else
-    ( :; $VALGRIND multi_file $DB_HDF5 ) >"$at_stdout" 2>"$at_stderr"
+    ( :; testsilock `pwd` $DB_HDF5 ) >"$at_stdout" 2>"$at_stderr"
     at_status=$?
 fi
 
 at_failed=false
-$at_diff "$at_devnull" "$at_stderr" || at_failed=:
+echo stderr:; cat "$at_stderr"
 echo stdout:; cat "$at_stdout"
 case $at_status in
    77) echo 77 > "$at_status_file"; exit 77;;
@@ -4971,10 +4968,10 @@ $at_traceon
     at_status=`cat "$at_status_file"`
     ;;
 
-  60 ) # 60. testsuite.at:253: testall -medium
+  60 ) # 60. testsuite.at:253: multi_file
     at_setup_line='testsuite.at:253'
-    at_desc="testall -medium"
-    $at_quiet $ECHO_N " 60: testall -medium                                $ECHO_C"
+    at_desc="multi_file"
+    $at_quiet $ECHO_N " 60: multi_file                                     $ECHO_C"
     at_xfail=no
     echo "#                             -*- compilation -*-" >> "$at_group_log"
     (
@@ -4983,12 +4980,12 @@ $at_traceon
 
 
 $at_traceoff
-echo "$at_srcdir/testsuite.at:255: \$VALGRIND testall -medium \$DB_HDF5"
+echo "$at_srcdir/testsuite.at:255: \$VALGRIND multi_file \$DB_HDF5"
 echo testsuite.at:255 >"$at_check_line_file"
 
 at_trace_this=
 if test -n "$at_traceon"; then
-    case "$VALGRIND testall -medium $DB_HDF5" in
+    case "$VALGRIND multi_file $DB_HDF5" in
         *'
 '*) echo 'Not enabling shell tracing (command contains an embedded newline)' ;;
  *) at_trace_this=yes ;;
@@ -4996,12 +4993,12 @@ if test -n "$at_traceon"; then
 fi
 
 if test -n "$at_trace_this"; then
-    ( $at_traceon; $VALGRIND testall -medium $DB_HDF5 ) >"$at_stdout" 2>"$at_stder1"
+    ( $at_traceon; $VALGRIND multi_file $DB_HDF5 ) >"$at_stdout" 2>"$at_stder1"
     at_status=$?
     grep '^ *+' "$at_stder1" >&2
     grep -v '^ *+' "$at_stder1" >"$at_stderr"
 else
-    ( :; $VALGRIND testall -medium $DB_HDF5 ) >"$at_stdout" 2>"$at_stderr"
+    ( :; $VALGRIND multi_file $DB_HDF5 ) >"$at_stdout" 2>"$at_stderr"
     at_status=$?
 fi
 
@@ -5029,10 +5026,10 @@ $at_traceon
     at_status=`cat "$at_status_file"`
     ;;
 
-  61 ) # 61. testsuite.at:257: testall -large
+  61 ) # 61. testsuite.at:257: testall -medium
     at_setup_line='testsuite.at:257'
-    at_desc="testall -large"
-    $at_quiet $ECHO_N " 61: testall -large                                 $ECHO_C"
+    at_desc="testall -medium"
+    $at_quiet $ECHO_N " 61: testall -medium                                $ECHO_C"
     at_xfail=no
     echo "#                             -*- compilation -*-" >> "$at_group_log"
     (
@@ -5041,8 +5038,66 @@ $at_traceon
 
 
 $at_traceoff
-echo "$at_srcdir/testsuite.at:259: \$VALGRIND testall -large \$DB_HDF5"
+echo "$at_srcdir/testsuite.at:259: \$VALGRIND testall -medium \$DB_HDF5"
 echo testsuite.at:259 >"$at_check_line_file"
+
+at_trace_this=
+if test -n "$at_traceon"; then
+    case "$VALGRIND testall -medium $DB_HDF5" in
+        *'
+'*) echo 'Not enabling shell tracing (command contains an embedded newline)' ;;
+ *) at_trace_this=yes ;;
+    esac
+fi
+
+if test -n "$at_trace_this"; then
+    ( $at_traceon; $VALGRIND testall -medium $DB_HDF5 ) >"$at_stdout" 2>"$at_stder1"
+    at_status=$?
+    grep '^ *+' "$at_stder1" >&2
+    grep -v '^ *+' "$at_stder1" >"$at_stderr"
+else
+    ( :; $VALGRIND testall -medium $DB_HDF5 ) >"$at_stdout" 2>"$at_stderr"
+    at_status=$?
+fi
+
+at_failed=false
+$at_diff "$at_devnull" "$at_stderr" || at_failed=:
+echo stdout:; cat "$at_stdout"
+case $at_status in
+   77) echo 77 > "$at_status_file"; exit 77;;
+   0) ;;
+   *) echo "$at_srcdir/testsuite.at:259: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+
+  echo 1 > "$at_status_file"
+  exit 1
+fi
+
+$at_traceon
+
+      $at_traceoff
+      $at_times_p && times >"$at_times_file"
+    ) 5>&1 2>&1 | eval $at_tee_pipe
+    at_status=`cat "$at_status_file"`
+    ;;
+
+  62 ) # 62. testsuite.at:261: testall -large
+    at_setup_line='testsuite.at:261'
+    at_desc="testall -large"
+    $at_quiet $ECHO_N " 62: testall -large                                 $ECHO_C"
+    at_xfail=no
+    echo "#                             -*- compilation -*-" >> "$at_group_log"
+    (
+      echo "62. testsuite.at:261: testing ..."
+      $at_traceon
+
+
+$at_traceoff
+echo "$at_srcdir/testsuite.at:263: \$VALGRIND testall -large \$DB_HDF5"
+echo testsuite.at:263 >"$at_check_line_file"
 
 at_trace_this=
 if test -n "$at_traceon"; then
@@ -5069,7 +5124,7 @@ echo stdout:; cat "$at_stdout"
 case $at_status in
    77) echo 77 > "$at_status_file"; exit 77;;
    0) ;;
-   *) echo "$at_srcdir/testsuite.at:259: exit code was $at_status, expected 0"
+   *) echo "$at_srcdir/testsuite.at:263: exit code was $at_status, expected 0"
       at_failed=:;;
 esac
 if $at_failed; then
@@ -5377,7 +5432,7 @@ _ASBOX
   echo "Please send \`${at_testdir+${at_testdir}/}$as_me.log' and all information you think might help:"
   echo
   echo "   To: <visit-users@email.ornl.gov>"
-  echo "   Subject: [silo 4.7.1-pre1] $as_me:$at_fail_list${at_fail_list:+ failed${at_xpass_list:+,}}$at_xpass_list${at_xpass_list:+ passed unexpectedly}"
+  echo "   Subject: [silo 4.7.1-pre2] $as_me:$at_fail_list${at_fail_list:+ failed${at_xpass_list:+,}}$at_xpass_list${at_xpass_list:+ passed unexpectedly}"
   echo
   if test $at_debug_p = false; then
     echo
