fix autotest testing

diff --git a/tests/testdtypes b/tests/testdtypes
--- a/tests/testdtypes
+++ b/tests/testdtypes
@@ -86,10 +86,19 @@ done
 # Ensure we have Silo's 'browser' tool available
 #
 if [ ! -x $script_dir/../../bin/browser ]; then
-    echo "Silo's 'browser' tool is required and not found."
-    exit 1
+    if [ ! -x $script_dir/../tools/browser/browser ]; then
+        if [ ! -x $script_dir/../../../tools/browser/browser ]; then
+            echo "Silo's 'browser' tool is required and not found."
+            exit 1
+        else
+            browser=$(command -v $script_dir/../../../tools/browser/browser)
+        fi
+    else
+        browser=$(command -v $script_dir/../tools/browser/browser)
+    fi
+else
+    browser=$(command -v $script_dir/../../bin/browser)
 fi
-browser=$(command -v $script_dir/../../bin/browser)
 
 #
 # Loop over all files, variables and types with and without force single enabled
diff --git a/tests/testsilock b/tests/testsilock
--- a/tests/testsilock
+++ b/tests/testsilock
@@ -87,10 +87,19 @@ onehex=$(command -v $script_dir/onehex)
 # Ensure we have Silo's 'silock' tool available
 #
 if [ ! -x $script_dir/../../bin/silock ]; then
-    echo "Silo's 'silock' tool is required and not found."
-    exit 1
+    if [ ! -x $script_dir/../tools/silock/silock ]; then
+        if [ ! -x $script_dir/../../../tools/silock/silock ]; then
+            echo "Silo's 'silock' tool is required and not found."
+            exit 1
+        else
+            silock=$(command -v $script_dir/../../../tools/silock/silock)
+        fi
+    else
+        silock=$(command -v $script_dir/../tools/silock/silock)
+    fi
+else
+    silock=$(command -v $script_dir/../../bin/silock)
 fi
-silock=$(command -v $script_dir/../../bin/silock)
 
 result=0
 for driver in DB_PDB "$1"; do
